/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SistemasRouteImport } from './routes/sistemas'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as ContabilidadeRouteImport } from './routes/contabilidade'
import { Route as ConsultoriaRouteImport } from './routes/consultoria'
import { Route as IndexRouteImport } from './routes/index'

const SistemasRoute = SistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContabilidadeRoute = ContabilidadeRouteImport.update({
  id: '/contabilidade',
  path: '/contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoriaRoute = ConsultoriaRouteImport.update({
  id: '/consultoria',
  path: '/consultoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultoria': typeof ConsultoriaRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/marcas': typeof MarcasRoute
  '/sistemas': typeof SistemasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultoria': typeof ConsultoriaRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/marcas': typeof MarcasRoute
  '/sistemas': typeof SistemasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultoria': typeof ConsultoriaRoute
  '/contabilidade': typeof ContabilidadeRoute
  '/marcas': typeof MarcasRoute
  '/sistemas': typeof SistemasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consultoria' | '/contabilidade' | '/marcas' | '/sistemas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consultoria' | '/contabilidade' | '/marcas' | '/sistemas'
  id:
    | '__root__'
    | '/'
    | '/consultoria'
    | '/contabilidade'
    | '/marcas'
    | '/sistemas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultoriaRoute: typeof ConsultoriaRoute
  ContabilidadeRoute: typeof ContabilidadeRoute
  MarcasRoute: typeof MarcasRoute
  SistemasRoute: typeof SistemasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sistemas': {
      id: '/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof SistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidade': {
      id: '/contabilidade'
      path: '/contabilidade'
      fullPath: '/contabilidade'
      preLoaderRoute: typeof ContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultoria': {
      id: '/consultoria'
      path: '/consultoria'
      fullPath: '/consultoria'
      preLoaderRoute: typeof ConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultoriaRoute: ConsultoriaRoute,
  ContabilidadeRoute: ContabilidadeRoute,
  MarcasRoute: MarcasRoute,
  SistemasRoute: SistemasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
